api_platform:
    resource: .
    type: api_platform
    prefix: /api/v1

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

authentication_token:
    path: /login
    methods: ['POST']
